- name: all
  hosts: nodes
  become: yes
  become_user: root
  remote_user: vagrant
  tasks:
    - name: Create directory for ssh-keys
      ansible.builtin.file:
        state=directory
        mode=0700
        dest=/root/.ssh/

    - name: Adding rsa-key in /root/.ssh/authorized_keys
      ansible.builtin.copy:
        src: /home/ashubin/.ssh/id_rsa.pub
        dest: /root/.ssh/authorized_keys
        owner: root
        mode: '0600'
#        ignore_errors: yes

    - name: Checking DNS
      command: host -t A google.com

    - name: Installing tools
      ansible.builtin.apt:
         name:
           - git
           - curl
         state: present
         update_cache: yes


    - name: Installing docker
      shell: curl -fsSL get.docker.com -o get-docker.sh && chmod +x get-docker.sh && ./get-docker.sh

    - name: Add the current user to docker group
      user: name=vagrant append=yes groups=docker




